title: Your awesome title
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
#this_site: "http://54.184.72.230:4000"
this_site: "http://forosuru.github.io"

collections:
    events:
        output: false
    lang:
        output: true
    user:
        output: true
    event_types:
        output: true

